# Generated by Django 5.2.12 on 2026-03-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_acessorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório'},
        ),
    ]
