# Generated by Django 5.2.12 on 2026-04-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, related_name='veiculos', to='core.acessorio'),
        ),
    ]
